CREATE TABLE "MEMBER" (
	"M_NO"	NUMBER(10)		NOT NULL,
	"M_ID"	VARCHAR2(25)		NOT NULL,
	"M_PW"	VARCHAR2(60)		NOT NULL,
	"M_NAME"	VARCHAR2(25)		NOT NULL,
	"M_ADDRESS1"	VARCHAR2(150)		NOT NULL,
	"M_ADDRESS2"	VARCHAR2(60)		NOT NULL,
	"M_ZIPCODE"	VARCHAR2(10)		NOT NULL,
	"M_BIRTH"	DATE		NOT NULL,
	"M_GRADE"	VARCHAR2(10)		NOT NULL,
	"M_EMAIL"	VARCHAR2(25)		NOT NULL,
	"M_PHONE"	VARCHAR2(25)		NOT NULL,
	"POINT"	NUMBER(10)		NOT NULL,
	"M_DATE"	DATE		NOT NULL
);

CREATE TABLE "COUPON" (
	"C_NO"	NUMBER(10)		NOT NULL,
	"C_STARTDATE"	DATE		NOT NULL,
	"C_DUEDATE"	DATE		NOT NULL,
	"C_NAME"	VARCHAR2(90)		NOT NULL,
	"DC_PER"	NUMBER(10)		NOT NULL
);

CREATE TABLE "PURCHASE" (
	"PUR_NO"	NUMBER(10)		NOT NULL,
	"M_NO"	NUMBER(10)		NOT NULL,
	"PUR_TOT"	NUMBER(20)		NOT NULL,
	"PUR_DC"	NUMBER(20)		NOT NULL,
	"PUR_PAY"	NUMBER(20)		NOT NULL,
	"PAY_MENT"	VARCHAR2(30)		NOT NULL,
	"PUR_DATE"	DATE		NOT NULL,
	"PUR_DVADDRESS"	VARCHAR2(200)		NOT NULL,
	"PUR_DV"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "ORDERS" (
	"O_NO"	NUMBER(10)		NOT NULL,
	"PUR_NO"	NUMBER(10)		NOT NULL,
	"PRO_NO"	NUMBER(10)		NOT NULL,
	"QUANTITY"	NUMBER(10)		NOT NULL,
	"DISCOUNT"	NUMBER(20)		NOT NULL,
	"O_PRICE"	NUMBER(20)		NOT NULL,
	"O_PAY"	NUMBER(20)		NOT NULL,
	"USECOUPON"	NUMBER(20)		NOT NULL,
	"O_STATE"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "PRODUCT" (
	"PRO_NO"	NUMBER(10)		NOT NULL,
	"V_NO"	NUMBER(10)		NOT NULL,
	"PRICE"	VARCHAR2(25)		NOT NULL,
	"QUANTITY"	VARCHAR2(25)		NOT NULL,
	"CATEGORY"	VARCHAR2(25)		NOT NULL,
	"BANNERIMG"	VARCHAR2(300)		NOT NULL,
	"WISH"	NUMBER(10)		NOT NULL,
	"SELLCOUNT"	NUMBER(10)		NOT NULL,
	"PRO_HIT"	NUMBER(10)		NOT NULL,
	"BUSINESS_NAME"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "VENDOR" (
	"V_NO"	NUMBER(10)		NOT NULL,
	"M_NO"	NUMBER(10)		NOT NULL,
	"BUSINESS_NAME"	VARCHAR2(30)		NOT NULL,
	"V_ACCOUNT"	VARCHAR2(30)		NOT NULL,
	"BIZ_LICENSE"	VARCHAR2(30)		NOT NULL,
	"V_FAX"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "OWNEDCOUPON" (
	"M_NO"	NUMBER(10)		NOT NULL,
	"C_NO"	NUMBER(10)		NOT NULL
);

CREATE TABLE "WISHLIST" (
	"PRO_NO"	NUMBER(10)		NOT NULL,
	"M_NO"	NUMBER(10)		NOT NULL,
	"WISH_DATE"	DATE		NOT NULL
);

CREATE TABLE "EVENT" (
	"EV_NO"	NUMBER(10)		NOT NULL,
	"EV_STARTDATE"	DATE		NOT NULL,
	"EV_DUEDATE"	DATE		NOT NULL,
	"EV_BANNER"	VARCHAR2(300)		NOT NULL,
	"EV_PAGE"	VARCHAR2(40)		NOT NULL
);

CREATE TABLE "REVIEW" (
	"REV_NO"	NUMBER(10)		NOT NULL,
	"M_NO"	NUMBER(10)		NOT NULL,
	"REV_WRITER"	VARCHAR2(30)		NOT NULL,
	"REV_TITLE"	VARCHAR2(250)		NOT NULL,
	"REV_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REV_DATE"	DATE		NOT NULL,
	"REV_EVAL"	NUMBER(10)		NOT NULL,
	"REV_LIKE"	NUMBER(10)		NOT NULL
);

CREATE TABLE "REPLY_REVIEW" (
	"R_REV_NO"	NUMBER(10)		NOT NULL,
	"REV_NO"	NUMBER(10)		NOT NULL,
	"R_REV_WRITER"	VARCHAR2(30)		NOT NULL,
	"R_REV_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"R_REV_DATE"	DATE		NOT NULL
);

CREATE TABLE "COMMUNITY" (
	"COM_NO"	NUMBER(10)		NOT NULL,
	"M_NO"	NUMBER(10)		NOT NULL,
	"COM_WRITER"	VARCHAR2(30)		NOT NULL,
	"COM_TITLE"	VARCHAR2(250)		NOT NULL,
	"COM_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"COM_DATE"	DATE		NOT NULL,
	"COM_EVAL"	NUMBER(10)		NOT NULL,
	"COM_LIKE"	NUMBER(10)		NOT NULL
);

CREATE TABLE "REPLY_COMMNITY" (
	"R_COM_NO"	NUMBER(10)		NOT NULL,
	"COM_NO"	NUMBER(10)		NOT NULL,
	"R_COM_WRITER"	VARCHAR2(30)		NOT NULL,
	"R_COM_CONTENT"	VARCHAR2(250)		NOT NULL,
	"R_COM_DATE"	VARCHAR2(4000)		NOT NULL,
	"R_COM_HIT"	NUMBER(10)		NOT NULL,
	"R_COM_LIKE"	NUMBER(10)		NOT NULL
);

CREATE TABLE "QNA" (
	"Q_NO"	NUMBER(10)		NOT NULL,
	"M_NO"	NUMBER(10)		NOT NULL,
	"Q_WRITER"	VARCHAR2(30)		NOT NULL,
	"Q_TITLE"	VARCHAR2(250)		NOT NULL,
	"Q_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"Q_DATE"	DATE		NOT NULL,
	"Q_HIT"	NUMBER(10)		NOT NULL,
	"Q_CATEGORY"	VARCHAR2(30)		NOT NULL,
	"Q_OPEN_STATUS"	VARCHAR2(1)		NOT NULL
);

CREATE TABLE "REPLY_QNA" (
	"R_Q_NO"	NUMBER(10)		NOT NULL,
	"Q_NO"	NUMBER(10)		NOT NULL,
	"R_Q_TITLE"	VARCHAR2(250)		NOT NULL,
	"R_Q_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"R_Q_WRITER"	VARCHAR2(30)		NOT NULL,
	"R_Q_DATE"	DATE		NOT NULL,
	"R_Q_HIT"	NUMBER(5)		NOT NULL,
	"R_Q_LIKE"	NUMBER(5)		NOT NULL
);

CREATE TABLE "NOTICE" (
	"N_NO"	NUMBER(10)		NOT NULL,
	"N_TITLE"	VARCHAR2(250)		NOT NULL,
	"N_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"N_DATE"	DATE		NOT NULL,
	"N_HIT"	NUMBER(10)		NOT NULL
);

CREATE TABLE "AUTHORITY" (
	"M_NO"	NUMBER(10)		NOT NULL,
	"AUTH"	VARCHAR2(15)		NOT NULL
);

CREATE TABLE "REVIEW_IMG" (
	"REV_NO"	NUMBER(10)		NOT NULL,
	"REV_IMG_PATH1"	VARCHAR2(90)		NULL,
	"REV_IMG_PATH2"	VARCHAR2(90)		NULL,
	"REV_IMG_PATH3"	VARCHAR2(90)		NULL,
	"REV_IMG_PATH4"	VARCHAR2(90)		NULL,
	"REV_IMG_PATH5"	VARCHAR2(90)		NULL
);

CREATE TABLE "QNA_IMG" (
	"Q_NO"	NUMBER(10)		NOT NULL,
	"Q_IMG_PATH1"	VARCHAR2(90)		NULL,
	"Q_IMG_PATH2"	VARCHAR2(90)		NULL,
	"Q_IMG_PATH3"	VARCHAR2(90)		NULL,
	"Q_IMG_PATH4"	VARCHAR2(90)		NULL,
	"Q_IMG_PATH5"	VARCHAR2(90)		NULL
);

CREATE TABLE "COMM_IMG" (
	"COM_NO"	NUMBER(10)		NOT NULL,
	"COMM_IMG_PATH1"	VARCHAR2(90)		NULL,
	"COMM_IMG_PATH2"	VARCHAR2(90)		NULL,
	"COMM_IMG_PATH3"	VARCHAR2(90)		NULL,
	"COMM_IMG_PATH4"	VARCHAR2(90)		NULL,
	"COMM_IMG_PATH5"	VARCHAR2(90)		NULL
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"M_NO"
);

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"C_NO"
);

ALTER TABLE "PURCHASE" ADD CONSTRAINT "PK_PURCHASE" PRIMARY KEY (
	"PUR_NO"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY (
	"O_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRO_NO"
);

ALTER TABLE "VENDOR" ADD CONSTRAINT "PK_VENDOR" PRIMARY KEY (
	"V_NO"
);

ALTER TABLE "OWNEDCOUPON" ADD CONSTRAINT "PK_OWNEDCOUPON" PRIMARY KEY (
	"M_NO",
	"C_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"PRO_NO",
	"M_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EV_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REV_NO"
);

ALTER TABLE "REPLY_REVIEW" ADD CONSTRAINT "PK_REPLY_REVIEW" PRIMARY KEY (
	"R_REV_NO"
);

ALTER TABLE "COMMUNITY" ADD CONSTRAINT "PK_COMMUNITY" PRIMARY KEY (
	"COM_NO"
);

ALTER TABLE "REPLY_COMMNITY" ADD CONSTRAINT "PK_REPLY_COMMNITY" PRIMARY KEY (
	"R_COM_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY (
	"Q_NO"
);

ALTER TABLE "REPLY_QNA" ADD CONSTRAINT "PK_REPLY_QNA" PRIMARY KEY (
	"R_Q_NO"
);

ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY (
	"N_NO"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"M_NO"
);

ALTER TABLE "REVIEW_IMG" ADD CONSTRAINT "PK_REVIEW_IMG" PRIMARY KEY (
	"REV_NO"
);

ALTER TABLE "QNA_IMG" ADD CONSTRAINT "PK_QNA_IMG" PRIMARY KEY (
	"Q_NO"
);

ALTER TABLE "COMM_IMG" ADD CONSTRAINT "PK_COMM_IMG" PRIMARY KEY (
	"COM_NO"
);

ALTER TABLE "PURCHASE" ADD CONSTRAINT "FK_MEMBER_TO_PURCHASE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_PURCHASE_TO_ORDERS_1" FOREIGN KEY (
	"PUR_NO"
)
REFERENCES "PURCHASE" (
	"PUR_NO"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_PRODUCT_TO_ORDERS_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_VENDOR_TO_PRODUCT_1" FOREIGN KEY (
	"V_NO"
)
REFERENCES "VENDOR" (
	"V_NO"
);

ALTER TABLE "VENDOR" ADD CONSTRAINT "FK_MEMBER_TO_VENDOR_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "OWNEDCOUPON" ADD CONSTRAINT "FK_MEMBER_TO_OWNEDCOUPON_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "OWNEDCOUPON" ADD CONSTRAINT "FK_COUPON_TO_OWNEDCOUPON_1" FOREIGN KEY (
	"C_NO"
)
REFERENCES "COUPON" (
	"C_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_PRODUCT_TO_WISHLIST_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBER_TO_WISHLIST_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "REPLY_REVIEW" ADD CONSTRAINT "FK_REVIEW_TO_REPLY_REVIEW_1" FOREIGN KEY (
	"REV_NO"
)
REFERENCES "REVIEW" (
	"REV_NO"
);

ALTER TABLE "COMMUNITY" ADD CONSTRAINT "FK_MEMBER_TO_COMMUNITY_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "REPLY_COMMNITY" ADD CONSTRAINT "FK_COMMUNITY_TO_REPLY_COMMNITY_1" FOREIGN KEY (
	"COM_NO"
)
REFERENCES "COMMUNITY" (
	"COM_NO"
);

ALTER TABLE "QNA" ADD CONSTRAINT "FK_MEMBER_TO_QNA_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "REPLY_QNA" ADD CONSTRAINT "FK_QNA_TO_REPLY_QNA_1" FOREIGN KEY (
	"Q_NO"
)
REFERENCES "QNA" (
	"Q_NO"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "FK_MEMBER_TO_AUTHORITY_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBER" (
	"M_NO"
);

ALTER TABLE "REVIEW_IMG" ADD CONSTRAINT "FK_REVIEW_TO_REVIEW_IMG_1" FOREIGN KEY (
	"REV_NO"
)
REFERENCES "REVIEW" (
	"REV_NO"
);

ALTER TABLE "QNA_IMG" ADD CONSTRAINT "FK_QNA_TO_QNA_IMG_1" FOREIGN KEY (
	"Q_NO"
)
REFERENCES "QNA" (
	"Q_NO"
);

ALTER TABLE "COMM_IMG" ADD CONSTRAINT "FK_COMMUNITY_TO_COMM_IMG_1" FOREIGN KEY (
	"COM_NO"
)
REFERENCES "COMMUNITY" (
	"COM_NO"
);

