

CREATE TABLE "MEMBERS" (
	"M_NO"	NUMBER(20)		NOT NULL,
	"M_ID"	VARCHAR2(25)		NOT NULL UNIQUE,
	"M_PW"	VARCHAR2(60)		NOT NULL,
	"M_NAME"	VARCHAR2(25)		NOT NULL,
	"M_ADDRESS1"	VARCHAR2(150)		NOT NULL,
	"M_ADDRESS2"	VARCHAR2(60)		NOT NULL,
	"M_ZIPCODE"	VARCHAR2(10)		NOT NULL,
	"M_BIRTH"	TIMESTAMP		NOT NULL,
	"M_GRADE"	VARCHAR2(10)		NOT NULL,
	"M_EMAIL"	VARCHAR2(25)		NOT NULL,
	"M_PHONE"	VARCHAR2(25)		NOT NULL,
	"M_POINT"	NUMBER(10)		NOT NULL,
	"M_DATE"	TIMESTAMP		NOT NULL
);

CREATE TABLE "COUPON" (
	"C_NO"	NUMBER(20)		NOT NULL,
	"C_STARTDATE"	TIMESTAMP		NOT NULL,
	"C_DUEDATE"	TIMESTAMP		NOT NULL,
	"C_NAME"	VARCHAR2(90)		NOT NULL,
	"C_DCPER"	NUMBER(10)		NOT NULL
);

CREATE TABLE "PURCHASE" (
	"PUR_NO"	NUMBER(20)		NOT NULL,
	"M_NO"	NUMBER(20)		NOT NULL,
	"PUR_TOT"	NUMBER(20)		NOT NULL,
	"PUR_DC"	NUMBER(20)		NOT NULL,
	"PUR_PAY"	NUMBER(20)		NOT NULL,
	"PUR_PAYMENT"	VARCHAR2(30)		NOT NULL,
	"PUR_DATE"	TIMESTAMP		NOT NULL,
	"PUR_DVADDRESS"	VARCHAR2(200)		NOT NULL,
	"PUR_DV"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "ORDERS" (
	"O_NO"	NUMBER(20)		NOT NULL,
	"PUR_NO"	NUMBER(20)		NOT NULL,
	"PRO_NO"	NUMBER(20)		NOT NULL,
	"O_QUANTITY"	NUMBER(10)		NOT NULL,
	"O_DISCOUNT"	NUMBER(20)		NOT NULL,
	"O_PRICE"	NUMBER(20)		NOT NULL,
	"O_PAY"	NUMBER(20)		NOT NULL,
	"O_USECOUPON"	NUMBER(20)		NOT NULL,
	"O_STATE"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "PRODUCT" (
	"PRO_NO"	NUMBER(20)		NOT NULL,
	"V_NO"	NUMBER(20)		NOT NULL,
	"P_C_NO"	NUMBER(20)		NOT NULL,
	"PRO_PRICE"	VARCHAR2(25)		NOT NULL,
	"PRO_QUANTITY"	VARCHAR2(25)		NOT NULL,

	"PRO_BANNERIMG"	VARCHAR2(300)		NOT NULL,
	"PRO_WISH"	NUMBER(10)		NOT NULL,
	"PRO_SELLCOUNT"	NUMBER(10)		NOT NULL,
	"PRO_HIT"	NUMBER(10)		NOT NULL,
	"PRO_BIZNAME"	VARCHAR2(30)		NOT NULL
);


CREATE TABLE "VENDOR" (
	"V_NO"	NUMBER(20)		NOT NULL,
	"M_NO"	NUMBER(20)		NOT NULL,
	"V_BIZNAME"	VARCHAR2(30)		NOT NULL,
	"V_ACCOUNT"	VARCHAR2(30)		NOT NULL,
	"V_LICENSE"	VARCHAR2(30)		NOT NULL,
	"V_FAX"	VARCHAR2(20)		NOT NULL
);

CREATE TABLE "OWNEDCOUPON" (
	"M_NO"	NUMBER(20)		NOT NULL,
	"C_NO"	NUMBER(20)		NOT NULL
);

CREATE TABLE "WISHLIST" (
	"PRO_NO"	NUMBER(20)		NOT NULL,
	"M_NO"	NUMBER(20)		NOT NULL,
	"WISH_DATE"	TIMESTAMP		NOT NULL
);

CREATE TABLE "EVENT" (
	"EV_NO"	NUMBER(20)		NOT NULL,
	"EV_STARTDATE"	TIMESTAMP		NOT NULL,
	"EV_DUEDATE"	TIMESTAMP		NOT NULL,
	"EV_BANNER"	VARCHAR2(300)		NOT NULL,
	"EV_PAGE"	VARCHAR2(40)		NOT NULL
);

CREATE TABLE "AUTHORITY" (
    "M_ID"	VARCHAR2(25)		NOT NULL UNIQUE,
	"AUTH"	VARCHAR2(15)		NOT NULL
);

CREATE TABLE "PRODUCT_IMGS" (
	"PRO_IMG_NO"	NUMBER(20)		NOT NULL,
	"PRO_NO"	NUMBER(20)		NOT NULL,
	"PRO_IMG_PATH"	VARCHAR2(90)		NOT NULL
);

CREATE TABLE "POINTS" (
	"PT_NO"	NUMBER(20)		NOT NULL,
	"M_NO"	NUMBER(20)		NOT NULL,
	"PT_CHANGE"	CHAR(1)		NOT NULL,
	"PT_AMOUNT"	NUMBER(22)		NOT NULL,
	"PT_REASON"	VARCHAR2(90)		NOT NULL,
	"PT_DATE"	TIMESTAMP		NOT NULL
);

CREATE TABLE "BOARD_IMGS" (
	"B_IMG_NO"	NUMBER(20)		NOT NULL,
	"B_NO"	NUMBER(20)		NOT NULL,
	"B_IMG_PATH"	VARCHAR2(90)		NOT NULL
);

CREATE TABLE "BOARD" (
	"B_NO"	NUMBER(20)		NOT NULL,
	"M_NO"	NUMBER(20)		NOT NULL,
	"B_C_NO"	NUMBER(20)		NOT NULL,
	"B_WRITER"	VARCHAR2(30)		NOT NULL,
	"B_TITLE"	VARCHAR2(250)		NOT NULL,
	"B_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"B_DATE"	TIMESTAMP		NOT NULL,
	"B_LIKE"	NUMBER(10)		NOT NULL,
	"B_HIT"	NUMBER(10)		NOT NULL,
	"B_EVAL"	NUMBER(3)		NULL,
	"PRO_NO"	NUMBER(20)		NULL
);




CREATE TABLE "BOARD_CATEGORY" (
	"B_C_NO"	NUMBER(20)		NOT NULL,
	"B_C_NAME"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "REPLYS" (
	"R_NO"	NUMBER(20)		NOT NULL,
	"B_NO"	NUMBER(20)		NOT NULL,
    "M_NO"	NUMBER(20)		NOT NULL,
	"R_WRITER"	VARCHAR2(30)		NOT NULL,
	"R_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"R_DATE"	TIMESTAMP		NOT NULL,
	"R_LIKE"	NUMBER(10)		NOT NULL,
	"R_GROUP"	NUMBER(20)		NULL,
	"R_STEP"	NUMBER(10)		NULL,
	"R_INDENT"	NUMBER(10)		NULL
);

CREATE SEQUENCE M_SEQ;
CREATE SEQUENCE C_SEQ;
CREATE SEQUENCE PUR_SEQ;
CREATE SEQUENCE O_SEQ;
CREATE SEQUENCE PRO_SEQ;
CREATE SEQUENCE V_SEQ;
CREATE SEQUENCE EV_SEQ;
CREATE SEQUENCE PRO_IMG_SEQ;
CREATE SEQUENCE PT_SEQ;
CREATE SEQUENCE B_IMG_SEQ;
CREATE SEQUENCE B_SEQ;
CREATE SEQUENCE B_C_SEQ;
CREATE SEQUENCE P_C_SEQ;
CREATE SEQUENCE R_SEQ;
CREATE SEQUENCE P_SEQ;

ALTER TABLE BOARD MODIFY (B_LIKE DEFAULT 0);
ALTER TABLE BOARD MODIFY (B_HIT DEFAULT 0);
ALTER TABLE AUTHORITY MODIFY (AUTH DEFAULT 'ROLE_USER');
ALTER TABLE PRODUCT MODIFY (PRO_HIT DEFAULT 0);
ALTER TABLE ORDERS MODIFY (O_DISCOUNT DEFAULT 0);
ALTER TABLE PURCHASE MODIFY (PUR_DC DEFAULT 0);
ALTER TABLE COUPON MODIFY (C_DCPER	 DEFAULT 0);
ALTER TABLE MEMBERS MODIFY (M_POINT DEFAULT 0);
ALTER TABLE MEMBERS MODIFY (M_GRADE	 DEFAULT 'SILVER');
ALTER TABLE REPLYS MODIFY (R_LIKE DEFAULT 0);
ALTER TABLE REPLYS MODIFY (R_GROUP DEFAULT 0);
ALTER TABLE REPLYS MODIFY (R_STEP DEFAULT 0);
ALTER TABLE REPLYS MODIFY (R_INDENT DEFAULT 0);


CREATE TABLE "PROFIT" (
	"P_DATE"	DATE		NOT NULL,
	"P_PRICE"	NUMBER(20)		NOT NULL
);

CREATE TABLE "PRODUCT_CATEGORY" (
	"P_C_NO"	NUMBER(2)		NOT NULL,
	"P_C_NAME"	VARCHAR2(40)		NOT NULL
);

ALTER TABLE "MEMBERS" ADD CONSTRAINT "PK_MEMBERS" PRIMARY KEY (
	"M_NO"
);

ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY (
	"C_NO"
);

ALTER TABLE "PURCHASE" ADD CONSTRAINT "PK_PURCHASE" PRIMARY KEY (
	"PUR_NO"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "PK_ORDERS" PRIMARY KEY (
	"O_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRO_NO"
);

ALTER TABLE "VENDOR" ADD CONSTRAINT "PK_VENDOR" PRIMARY KEY (
	"V_NO"
);

ALTER TABLE "OWNEDCOUPON" ADD CONSTRAINT "PK_OWNEDCOUPON" PRIMARY KEY (
	"M_NO",
	"C_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "PK_WISHLIST" PRIMARY KEY (
	"PRO_NO",
	"M_NO"
);

ALTER TABLE "EVENT" ADD CONSTRAINT "PK_EVENT" PRIMARY KEY (
	"EV_NO"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "PK_AUTHORITY" PRIMARY KEY (
	"M_ID"
);

ALTER TABLE "PRODUCT_IMGS" ADD CONSTRAINT "PK_PRODUCT_IMGS" PRIMARY KEY (
	"PRO_IMG_NO"
);

ALTER TABLE "POINTS" ADD CONSTRAINT "PK_POINTS" PRIMARY KEY (
	"PT_NO"
);

ALTER TABLE "BOARD_IMGS" ADD CONSTRAINT "PK_BOARD_IMGS" PRIMARY KEY (
	"B_IMG_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"B_NO"
);

ALTER TABLE "BOARD_CATEGORY" ADD CONSTRAINT "PK_BOARD_CATEGORY" PRIMARY KEY (
	"B_C_NO"
);

ALTER TABLE "REPLYS" ADD CONSTRAINT "PK_REPLYS" PRIMARY KEY (
	"R_NO"
);

ALTER TABLE "PROFIT" ADD CONSTRAINT "PK_PROFIT" PRIMARY KEY (
	"P_DATE"
);

ALTER TABLE "PRODUCT_CATEGORY" ADD CONSTRAINT "PK_PRODUCT_CATEGORY" PRIMARY KEY (
	"P_C_NO"
);

ALTER TABLE "PURCHASE" ADD CONSTRAINT "FK_MEMBERS_TO_PURCHASE_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBERS" (
	"M_NO"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_PURCHASE_TO_ORDERS_1" FOREIGN KEY (
	"PUR_NO"
)
REFERENCES "PURCHASE" (
	"PUR_NO"
);

ALTER TABLE "ORDERS" ADD CONSTRAINT "FK_PRODUCT_TO_ORDERS_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_VENDOR_TO_PRODUCT_1" FOREIGN KEY (
	"V_NO"
)
REFERENCES "VENDOR" (
	"V_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "FK_PRO_CATE_TO_PRO_1" FOREIGN KEY (
	"P_C_NO"
)
REFERENCES "PRODUCT_CATEGORY" (
	"P_C_NO"
);

ALTER TABLE "VENDOR" ADD CONSTRAINT "FK_MEMBERS_TO_VENDOR_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBERS" (
	"M_NO"
);

ALTER TABLE "OWNEDCOUPON" ADD CONSTRAINT "FK_MEMBERS_TO_OWNEDCOUPON_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBERS" (
	"M_NO"
);

ALTER TABLE "OWNEDCOUPON" ADD CONSTRAINT "FK_COUPON_TO_OWNEDCOUPON_1" FOREIGN KEY (
	"C_NO"
)
REFERENCES "COUPON" (
	"C_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_PRODUCT_TO_WISHLIST_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "WISHLIST" ADD CONSTRAINT "FK_MEMBERS_TO_WISHLIST_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBERS" (
	"M_NO"
);

ALTER TABLE "AUTHORITY" ADD CONSTRAINT "FK_MEMBERS_TO_AUTHORITY_1" FOREIGN KEY (
	"M_ID"
)
REFERENCES "MEMBERS" (
	"M_ID"
);

ALTER TABLE "PRODUCT_IMGS" ADD CONSTRAINT "FK_PRODUCT_TO_PRODUCT_IMGS_1" FOREIGN KEY (
	"PRO_NO"
)
REFERENCES "PRODUCT" (
	"PRO_NO"
);

ALTER TABLE "POINTS" ADD CONSTRAINT "FK_MEMBERS_TO_POINTS_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBERS" (
	"M_NO"
);

ALTER TABLE "BOARD_IMGS" ADD CONSTRAINT "FK_BOARD_TO_BOARD_IMGS_1" FOREIGN KEY (
	"B_NO"
)
REFERENCES "BOARD" (
	"B_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_MEMBERS_TO_BOARD_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBERS" (
	"M_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "FK_BOARD_CATEGORY_TO_BOARD_1" FOREIGN KEY (
	"B_C_NO"
)
REFERENCES "BOARD_CATEGORY" (
	"B_C_NO"
);

ALTER TABLE "REPLYS" ADD CONSTRAINT "FK_BOARD_TO_REPLYS_1" FOREIGN KEY (
	"B_NO"
)
REFERENCES "BOARD" (
	"B_NO"
);
ALTER TABLE "REPLYS" ADD CONSTRAINT "FK_MEMBERS_TO_replys_1" FOREIGN KEY (
	"M_NO"
)
REFERENCES "MEMBERS" (
	"M_NO"
);

********************이미 실행한 경우 ******************************

CREATE SEQUENCE P_SEQ;

ALTER TABLE AUTHORITY DROP CONSTRAINT PK_AUTHORITY;
ALTER TABLE AUTHORITY DROP COLUMN M_NO;
ALTER TABLE authority ADD (M_ID VARCHAR2(25) NOT NULL unique);

ALTER TABLE members MODIFY (M_ID VARCHAR2(25) unique);


ALTER TABLE "AUTHORITY" ADD CONSTRAINT "FK_MEMBERS_TO_Authority_1" FOREIGN KEY (
	"M_ID"
)
REFERENCES "MEMBERS" (
		"M_ID"
);

ALTER TABLE BOARD MODIFY (B_LIKE DEFAULT 0);
ALTER TABLE BOARD MODIFY (B_HIT DEFAULT 0);
ALTER TABLE AUTHORITY MODIFY (AUTH DEFAULT 'ROLE_USER');
ALTER TABLE PRODUCT MODIFY (PRO_HIT DEFAULT 0);
ALTER TABLE ORDERS MODIFY (O_DISCOUNT DEFAULT 0);
ALTER TABLE PURCHASE MODIFY (PUR_DC DEFAULT 0);
ALTER TABLE COUPON MODIFY (C_DCPER	 DEFAULT 0);
ALTER TABLE MEMBERS MODIFY (M_POINT DEFAULT 0);
ALTER TABLE MEMBERS MODIFY (M_GRADE	 DEFAULT 'SILVER');
ALTER TABLE REPLYS MODIFY (R_LIKE DEFAULT 0);
ALTER TABLE REPLYS MODIFY (R_GROUP DEFAULT 0);
ALTER TABLE REPLYS MODIFY (R_STEP DEFAULT 0);
ALTER TABLE REPLYS MODIFY (R_INDENT DEFAULT 0);
commit;
